### ISSUE TITLE
Hi from APIs.guru

### ISSUE THREAD

**Issue by IvanGoncharov** [kenmick/SwaggerParser#1]
Hi @kenmick,

I didn't found your email so decided to open this issue 😄

You project is very interesting but see that you not only generate statistics but aggregate Swagger specs from different sources.
And even [couple specs](https://github.com/kenmick/SwaggerParser/search?utf8=%E2%9C%93&q=x-origin) from [my project](https://github.com/APIs-guru/api-models) and to keep them in sync you can use this [API](https://github.com/APIs-guru/api-models/blob/master/API.md).

Collaborating on searching/scraping/filtering specs would be great.
For example, I scrape Github and found 7000+ unique Swagger specs:
https://morph.io/IvanGoncharov/API_specifications
But they still need to be validated and filtered, so I'm very interested in collaboration around this and similar projects.

I open this issue to make first contact so you can close it.
You can contract me on Hangouts(ivan.goncharov.ua@gmail.com) or Skype(ivangon4arov)

All best,
Ivan Goncharov

**Comment by kenmick** [comment]
@IvanGoncharov 
I have sent you an email, check it, please. :smile:
